version: "3.9"
services:
  frontend:
    container_name: movies-front
    build:
      context: ./
      dockerfile: Dockerfile
    image: movies-front
    networks:
      - frontend
    ports:
      - 8081:80
    restart: on-failure

networks:
  frontend:
